name: mdx-net

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pytorch=1.8.1
  - torchvision=0.9.1
  - jupyter
  - librosa=0.8
  - ffmpeg
  - onnxruntime
  - nvidia-apex

  - pip:
      - -r requirements.txt
